# fly.toml app configuration file generated for petfinder on 2023-08-29T21:03:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "petfinder"
primary_region = "qro"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
